# TCL File Generated by Component Editor 18.1
# Mon Jul 15 12:17:38 CEST 2024
# DO NOT MODIFY


# 
# mutrig_frame_assembly "MuTRiG Frame Assembly " v1.2.1
# Yifeng Wang 2024.07.15.12:17:38
# Assemble the MuTRiG frame from lvds receiver bytes. 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module mutrig_frame_assembly
# 
set_module_property DESCRIPTION "Assemble the MuTRiG frame from lvds receiver bytes. "
set_module_property NAME mutrig_frame_assembly
set_module_property VERSION 1.2.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Mu3e Data Plane/Modules"
set_module_property AUTHOR "Yifeng Wang"
set_module_property ICON_PATH ../drawings/20121123203030!Logo_drawing100.png
set_module_property DISPLAY_NAME "MuTRiG Frame Assembly "
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL frame_rcv_ip
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file frame_rcv_ip.vhd VHDL PATH frame_rcv_ip.vhd TOP_LEVEL_FILE
add_fileset_file crc16_calc.vhd VHDL PATH crc16_calc.vhd


# 
# parameters
# 
add_parameter DEBUG_BYPASS_ERROR NATURAL 0
set_parameter_property DEBUG_BYPASS_ERROR DEFAULT_VALUE 0
set_parameter_property DEBUG_BYPASS_ERROR DISPLAY_NAME DEBUG_BYPASS_ERROR
set_parameter_property DEBUG_BYPASS_ERROR TYPE NATURAL
set_parameter_property DEBUG_BYPASS_ERROR ENABLED false
set_parameter_property DEBUG_BYPASS_ERROR UNITS None
set_parameter_property DEBUG_BYPASS_ERROR ALLOWED_RANGES 0:2147483647
set_parameter_property DEBUG_BYPASS_ERROR HDL_PARAMETER true
add_parameter SIMULATION_EN NATURAL 0
set_parameter_property SIMULATION_EN DEFAULT_VALUE 0
set_parameter_property SIMULATION_EN DISPLAY_NAME SIMULATION_EN
set_parameter_property SIMULATION_EN TYPE NATURAL
set_parameter_property SIMULATION_EN ENABLED false
set_parameter_property SIMULATION_EN UNITS None
set_parameter_property SIMULATION_EN ALLOWED_RANGES 0:2147483647
set_parameter_property SIMULATION_EN HDL_PARAMETER true
add_parameter ASIC_ID NATURAL 0
set_parameter_property ASIC_ID DEFAULT_VALUE 0
set_parameter_property ASIC_ID DISPLAY_NAME ASIC_ID
set_parameter_property ASIC_ID TYPE NATURAL
set_parameter_property ASIC_ID UNITS None
set_parameter_property ASIC_ID ALLOWED_RANGES 0:2147483647
set_parameter_property ASIC_ID HDL_PARAMETER true


# 
# display items
# 


# 
# connection point rx8b1k
# 
add_interface rx8b1k avalon_streaming end
set_interface_property rx8b1k associatedClock clock_sink
set_interface_property rx8b1k associatedReset reset_sink
set_interface_property rx8b1k dataBitsPerSymbol 9
set_interface_property rx8b1k errorDescriptor ""
set_interface_property rx8b1k firstSymbolInHighOrderBits true
set_interface_property rx8b1k maxChannel 15
set_interface_property rx8b1k readyLatency 0
set_interface_property rx8b1k ENABLED true
set_interface_property rx8b1k EXPORT_OF ""
set_interface_property rx8b1k PORT_NAME_MAP ""
set_interface_property rx8b1k CMSIS_SVD_VARIABLES ""
set_interface_property rx8b1k SVD_ADDRESS_GROUP ""

add_interface_port rx8b1k asi_rx8b1k_data data Input 9
add_interface_port rx8b1k asi_rx8b1k_valid valid Input 1
add_interface_port rx8b1k asi_rx8b1k_channel channel Input 4
add_interface_port rx8b1k asi_rx8b1k_error error Input 3


# 
# connection point hit_type0
# 
add_interface hit_type0 avalon_streaming start
set_interface_property hit_type0 associatedClock clock_sink
set_interface_property hit_type0 associatedReset reset_sink
set_interface_property hit_type0 dataBitsPerSymbol 45
set_interface_property hit_type0 errorDescriptor ""
set_interface_property hit_type0 firstSymbolInHighOrderBits true
set_interface_property hit_type0 maxChannel 15
set_interface_property hit_type0 readyLatency 0
set_interface_property hit_type0 ENABLED true
set_interface_property hit_type0 EXPORT_OF ""
set_interface_property hit_type0 PORT_NAME_MAP ""
set_interface_property hit_type0 CMSIS_SVD_VARIABLES ""
set_interface_property hit_type0 SVD_ADDRESS_GROUP ""

add_interface_port hit_type0 aso_hit_type0_channel channel Output 4
add_interface_port hit_type0 aso_hit_type0_startofpacket startofpacket Output 1
add_interface_port hit_type0 aso_hit_type0_endofpacket endofpacket Output 1
add_interface_port hit_type0 aso_hit_type0_error error Output 3
add_interface_port hit_type0 aso_hit_type0_data data Output 45
add_interface_port hit_type0 aso_hit_type0_valid valid Output 1


# 
# connection point headerinfo
# 
add_interface headerinfo avalon_streaming start
set_interface_property headerinfo associatedClock clock_sink
set_interface_property headerinfo associatedReset reset_sink
set_interface_property headerinfo dataBitsPerSymbol 42
set_interface_property headerinfo errorDescriptor ""
set_interface_property headerinfo firstSymbolInHighOrderBits true
set_interface_property headerinfo maxChannel 0
set_interface_property headerinfo readyLatency 0
set_interface_property headerinfo ENABLED true
set_interface_property headerinfo EXPORT_OF ""
set_interface_property headerinfo PORT_NAME_MAP ""
set_interface_property headerinfo CMSIS_SVD_VARIABLES ""
set_interface_property headerinfo SVD_ADDRESS_GROUP ""

add_interface_port headerinfo aso_headerinfo_data data Output 42
add_interface_port headerinfo aso_headerinfo_valid valid Output 1
add_interface_port headerinfo aso_headerinfo_channel channel Output 4


# 
# connection point csr
# 
add_interface csr avalon end
set_interface_property csr addressUnits WORDS
set_interface_property csr associatedClock clock_sink
set_interface_property csr associatedReset reset_sink
set_interface_property csr bitsPerSymbol 8
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 0
set_interface_property csr maximumPendingWriteTransactions 0
set_interface_property csr readLatency 0
set_interface_property csr readWaitTime 1
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr writeWaitTime 0
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr CMSIS_SVD_VARIABLES ""
set_interface_property csr SVD_ADDRESS_GROUP ""

add_interface_port csr avs_csr_readdata readdata Output 32
add_interface_port csr avs_csr_read read Input 1
add_interface_port csr avs_csr_address address Input 1
add_interface_port csr avs_csr_waitrequest waitrequest Output 1
add_interface_port csr avs_csr_byteenable byteenable Input 4
add_interface_port csr avs_csr_write write Input 1
add_interface_port csr avs_csr_writedata writedata Input 32
set_interface_assignment csr embeddedsw.configuration.isFlash 0
set_interface_assignment csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr embeddedsw.configuration.isPrintableDevice 0


# 
# connection point ctrl
# 
add_interface ctrl avalon_streaming end
set_interface_property ctrl associatedClock clock_sink
set_interface_property ctrl associatedReset reset_sink
set_interface_property ctrl dataBitsPerSymbol 9
set_interface_property ctrl errorDescriptor ""
set_interface_property ctrl firstSymbolInHighOrderBits true
set_interface_property ctrl maxChannel 0
set_interface_property ctrl readyLatency 0
set_interface_property ctrl ENABLED true
set_interface_property ctrl EXPORT_OF ""
set_interface_property ctrl PORT_NAME_MAP ""
set_interface_property ctrl CMSIS_SVD_VARIABLES ""
set_interface_property ctrl SVD_ADDRESS_GROUP ""

add_interface_port ctrl asi_ctrl_data data Input 9
add_interface_port ctrl asi_ctrl_valid valid Input 1
add_interface_port ctrl asi_ctrl_ready ready Output 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink i_clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink i_rst reset Input 1

